name: Validate Finch
on: [push]

jobs:
  validate:
    name: Validate Source Code
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: finch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: finch
          install-command: npm ci

      - name: Run Unit tests
        run: npm run test:ci

      - name: Lint Code
        run: npm run lint
