name: Validate Reese
on:
  push:
    paths:
      - "reese/**"

jobs:
  validate:
    name: Validate Source Code
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: reese
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: reese
          install-command: npm ci

      - name: Lint Code
        run: npm run lint

      # TODO: Added step to run unit tests also
